export const GLOSSARY: Record<string, string> = {
  "V-Signal": "Value signal \u2014 measures originality and unique insight",
  "C-Context": "Contextual credibility \u2014 measures source reliability and factual grounding",
  "L-Slop": "Low-quality probability \u2014 detects AI-generated filler, clickbait, and noise",
  "WoT": "Web of Trust \u2014 your Nostr social graph used to weight content from trusted contacts",
  "D2A": "Device-to-Agent \u2014 encrypted protocol for AI agents to exchange content peer-to-peer",
  "Slop": "Low-quality, AI-generated, or misleading content identified by the filter",
  "Nostr": "Decentralized social protocol \u2014 Aegis publishes signals as Nostr events",
  "Serendipity": "Quality content outside your usual topics \u2014 expanding your perspective",
  "IC": "Internet Computer \u2014 blockchain where Aegis stores data and runs smart contracts",
  "Composite": "Overall quality score (0\u201310) combining V-Signal, C-Context, and L-Slop",
  "Filter Accuracy": "Percentage of evaluated content marked as quality over the last 7 days",
  "Slop Volume": "Number of low-quality items filtered out per day",
  "High signal": "Strong originality and unique insight (V-Signal \u2265 7)",
  "Rich context": "Reliable sourcing and factual grounding (C-Context \u2265 7)",
  "Low noise": "Minimal AI filler, clickbait, or fluff (L-Slop \u2264 2)",
  "High slop risk": "Likely AI-generated filler or clickbait (L-Slop \u2265 7)",
  "Original": "Highly original content with novel perspective (Originality \u2265 8)",
  "Insightful": "Provides meaningful analysis and deep insight (Insight \u2265 8)",
  "Credible": "Well-sourced and factually grounded (Credibility \u2265 8)",
};
