import type { ContentItem } from "@/lib/types/content";

export const SAMPLE_CONTENT: ContentItem[] = [
  { id: "1", owner: "", author: "@research_lab", avatar: "🔬", text: "New findings on transformer attention mechanisms show 23% improvement in long-context retrieval when using sliding window + global token hybrid approach. Paper with reproducible code: arxiv.org/abs/2402.xxxxx", source: "twitter", timestamp: "2m ago", scores: { originality: 8, insight: 9, credibility: 9, composite: 8.7 }, verdict: "quality", reason: "Novel research with reproducible code", createdAt: Date.now() - 120000, validated: false, flagged: false },
  { id: "2", owner: "", author: "@crypto_guru99", avatar: "🚀", text: "THIS COIN IS GOING TO 100X!!! DON'T MISS OUT!!! 🔥🔥🔥 LIKE AND RT FOR MORE ALPHA 💰💰💰", source: "twitter", timestamp: "5m ago", scores: { originality: 1, insight: 0, credibility: 1, composite: 0.7 }, verdict: "slop", reason: "Pump signal with no substance", createdAt: Date.now() - 300000, validated: false, flagged: false },
  { id: "3", owner: "", author: "@fintech_insider", avatar: "📊", text: "Analysis: Japan's FSA is quietly revising its stablecoin framework. Key change: registered issuers can now offer programmable USDC-equivalent tokens under revised PSA Article 2-5. This opens doors for DeFi-native compliance.", source: "twitter", timestamp: "8m ago", scores: { originality: 7, insight: 8, credibility: 8, composite: 7.6 }, verdict: "quality", reason: "Specific regulatory insight with references", createdAt: Date.now() - 480000, validated: false, flagged: false },
  { id: "4", owner: "", author: "@ai_news_bot", avatar: "🤖", text: "Top 10 AI tools you NEED in 2026: 1. ChatGPT 2. Claude 3. Midjourney 4. ... (thread 🧵)", source: "twitter", timestamp: "12m ago", scores: { originality: 1, insight: 2, credibility: 3, composite: 1.8 }, verdict: "slop", reason: "Listicle with no original analysis", createdAt: Date.now() - 720000, validated: false, flagged: false },
  { id: "5", owner: "", author: "@protocol_dev", avatar: "⚡", text: "Shipped a working implementation of ERC-4337 bundler that reduces UserOp gas by 40% through calldata compression. Key insight: most UserOps share common function selectors that can be dictionary-encoded.", source: "twitter", timestamp: "15m ago", scores: { originality: 9, insight: 8, credibility: 8, composite: 8.5 }, verdict: "quality", reason: "Original implementation with measurable improvement", createdAt: Date.now() - 900000, validated: false, flagged: false },
  { id: "6", owner: "", author: "@web3_influencer", avatar: "💎", text: "GM! Remember: you're early. The future is decentralized. Stay bullish, stay humble. Who's building today? 👇", source: "twitter", timestamp: "18m ago", scores: { originality: 0, insight: 0, credibility: 2, composite: 0.5 }, verdict: "slop", reason: "Generic motivational content with no information", createdAt: Date.now() - 1080000, validated: false, flagged: false },
  { id: "7", owner: "", author: "@security_researcher", avatar: "🛡️", text: "Critical vulnerability disclosed in popular AA wallet implementation: reentrancy in validateUserOp allows gas griefing. Patch available. If you're using EntryPoint v0.6, update immediately.", source: "twitter", timestamp: "22m ago", scores: { originality: 9, insight: 9, credibility: 10, composite: 9.3 }, verdict: "quality", reason: "Critical security disclosure with actionable guidance", createdAt: Date.now() - 1320000, validated: false, flagged: false },
  { id: "8", owner: "", author: "@motivation_daily", avatar: "✨", text: "Success isn't about money. It's about impact. Steve Jobs didn't build Apple for the money. What are YOU building? 🌟 #motivation", source: "twitter", timestamp: "25m ago", scores: { originality: 1, insight: 1, credibility: 1, composite: 1.0 }, verdict: "slop", reason: "Rehashed motivational quote", createdAt: Date.now() - 1500000, validated: false, flagged: false },
  { id: "9", owner: "", author: "@data_economist", avatar: "📈", text: "Interesting pattern: Base L2 TVL crossed $8B this week while gas costs averaged $0.001. The economic argument for L2 migration is becoming undeniable.", source: "twitter", timestamp: "30m ago", scores: { originality: 7, insight: 7, credibility: 7, composite: 7.0 }, verdict: "quality", reason: "Data-backed analysis with specific metrics", createdAt: Date.now() - 1800000, validated: false, flagged: false },
  { id: "10", owner: "", author: "@clickbait_farm", avatar: "📰", text: "You won't BELIEVE what this developer found in Ethereum's code... (link in bio)", source: "twitter", timestamp: "33m ago", scores: { originality: 0, insight: 0, credibility: 0, composite: 0.0 }, verdict: "slop", reason: "Clickbait with no substance", createdAt: Date.now() - 1980000, validated: false, flagged: false },
  { id: "11", owner: "", author: "@nostr_builder", avatar: "🌐", text: "Released NIP-78 relay implementation with support for parameterized replaceable events. 3x throughput improvement over reference. Rust source on GitHub.", source: "nostr", timestamp: "40m ago", scores: { originality: 8, insight: 7, credibility: 8, composite: 7.7 }, verdict: "quality", reason: "Original open source release with measurable improvement", createdAt: Date.now() - 2400000, validated: false, flagged: false },
  { id: "12", owner: "", author: "@shill_account", avatar: "💸", text: "Just aped into $PEPE2. This is the one. NFA but DYOR. Moonshot incoming 📈📈📈", source: "twitter", timestamp: "45m ago", scores: { originality: 0, insight: 0, credibility: 0, composite: 0.0 }, verdict: "slop", reason: "Shilling with no analysis", createdAt: Date.now() - 2700000, validated: false, flagged: false },
];
